import { supabase } from '../lib/supabase'
export type Product={id:string;company_id:string;name:string;sku:string|null;unit:string;current_cost:number;min_stock:number;active:boolean}
export type Warehouse={id:string;company_id:string;restaurant_id:string;name:string;location:string|null;active:boolean}
export type Stock={id:string;quantity:number;products:{name:string;unit:string;min_stock:number}|{name:string;unit:string;min_stock:number}[];warehouses:{name:string}|{name:string}[]}
export type Count={id:string;count_date:string;status:string;warehouses:{name:string}|{name:string}[]}
export type Movement={id:string;movement_type:string;quantity:number;reference:string|null;created_at:string;products:{name:string;unit:string}|{name:string;unit:string}[]}
export type Waste={id:string;quantity:number;reason:string;cost:number|null;occurred_at:string;products:{name:string;unit:string}|{name:string;unit:string}[]}
export async function getInventoryData(){if(!supabase)return{products:[],warehouses:[],stock:[],counts:[],movements:[],waste:[]};const[p,w,s,c,m,x]=await Promise.all([supabase.from('products').select('*').order('name'),supabase.from('warehouses').select('*').order('name'),supabase.from('stock_levels').select('id,quantity,products(name,unit,min_stock),warehouses(name)'),supabase.from('inventory_counts').select('id,count_date,status,warehouses(name)').order('count_date',{ascending:false}),supabase.from('stock_movements').select('id,movement_type,quantity,reference,created_at,products(name,unit)').order('created_at',{ascending:false}),supabase.from('waste_records').select('id,quantity,reason,cost,occurred_at,products(name,unit)').order('occurred_at',{ascending:false})]);const e=p.error||w.error||s.error||c.error||m.error||x.error;if(e)throw e;return{products:(p.data??[])as Product[],warehouses:(w.data??[])as Warehouse[],stock:(s.data??[])as unknown as Stock[],counts:(c.data??[])as unknown as Count[],movements:(m.data??[])as unknown as Movement[],waste:(x.data??[])as unknown as Waste[]}}
export async function saveInventory(table:'products'|'warehouses'|'inventory_counts'|'stock_movements'|'waste_records',value:Record<string,unknown>){if(!supabase)throw new Error('Supabase no está configurado');const q=value.id?supabase.from(table).update(value).eq('id',String(value.id)):supabase.from(table).insert(value);const{error}=await q;if(error)throw error}
