import { useEffect, useState } from 'react'
import { BriefcaseBusiness, Plus, UsersRound, X } from 'lucide-react'
import { getCompany, getDepartments, getPositions, saveDepartment, savePosition } from '../../services/settings-data'
import type { DepartmentRecord, PositionRecord } from '../../types/domain'
import { SettingsLayout } from './SettingsLayout'

type Editor = { kind:'department'; value:DepartmentRecord } | { kind:'position'; value:PositionRecord }

export function CatalogsSettings(){
  const [companyId,setCompanyId]=useState('');const [departments,setDepartments]=useState<DepartmentRecord[]>([]);const [positions,setPositions]=useState<PositionRecord[]>([]);const [editor,setEditor]=useState<Editor|null>(null);const [message,setMessage]=useState('')
  const load=async()=>{const [company,depts,jobs]=await Promise.all([getCompany(),getDepartments(),getPositions()]);setCompanyId(company?.id??'');setDepartments(depts);setPositions(jobs)}
  useEffect(()=>{load().catch(e=>setMessage(e.message))},[])
  const persist=async()=>{if(!editor)return;try{if(editor.kind==='department')await saveDepartment(editor.value);else await savePosition(editor.value);setEditor(null);setMessage('Catálogo actualizado correctamente.');await load()}catch(e){setMessage(e instanceof Error?e.message:'No se pudo guardar.')}}
  return <SettingsLayout eyebrow="Personal" title="Catálogos" description="Departamentos y puestos reutilizables para organizar el equipo.">
    {message&&<p className="mb-4 text-sm text-[#456052]">{message}</p>}
    <div className="grid xl:grid-cols-2 gap-5"><section className="card overflow-hidden"><div className="p-5 border-b flex items-center justify-between"><div className="flex items-center gap-3"><UsersRound className="text-[#39705a]"/><h2 className="font-semibold">Departamentos</h2></div><button onClick={()=>setEditor({kind:'department',value:{id:'',company_id:companyId,name:'',description:'',active:true}})} className="text-sm font-semibold text-[#315f4c] inline-flex gap-1"><Plus size={17}/> Añadir</button></div><div className="divide-y">{departments.map(item=><button key={item.id} onClick={()=>setEditor({kind:'department',value:item})} className="p-5 w-full text-left hover:bg-[#f8faf8]"><p className="font-semibold">{item.name}</p><p className="text-sm text-[#78827d] mt-1">{item.description||'Sin descripción'}</p></button>)}</div></section>
    <section className="card overflow-hidden"><div className="p-5 border-b flex items-center justify-between"><div className="flex items-center gap-3"><BriefcaseBusiness className="text-[#39705a]"/><h2 className="font-semibold">Puestos</h2></div><button onClick={()=>setEditor({kind:'position',value:{id:'',company_id:companyId,department_id:null,name:'',description:'',active:true}})} className="text-sm font-semibold text-[#315f4c] inline-flex gap-1"><Plus size={17}/> Añadir</button></div><div className="divide-y">{positions.map(item=><button key={item.id} onClick={()=>setEditor({kind:'position',value:item})} className="p-5 w-full text-left hover:bg-[#f8faf8]"><p className="font-semibold">{item.name}</p><p className="text-sm text-[#78827d] mt-1">{departments.find(d=>d.id===item.department_id)?.name||'Sin departamento'}</p></button>)}</div></section></div>
    {editor&&<div className="fixed inset-0 bg-[#183128]/35 z-50 flex justify-end" onMouseDown={()=>setEditor(null)}><div className="w-full max-w-lg h-full bg-[#fbfcfa] p-7 shadow-2xl" onMouseDown={e=>e.stopPropagation()}><div className="flex justify-between"><h2 className="text-2xl font-semibold">{editor.value.id?'Editar':'Crear'} {editor.kind==='department'?'departamento':'puesto'}</h2><button onClick={()=>setEditor(null)}><X/></button></div><label className="block text-sm font-medium mt-8">Nombre<input value={editor.value.name} onChange={e=>setEditor({...editor,value:{...editor.value,name:e.target.value}} as Editor)} className="mt-2 w-full rounded-xl border px-4 py-3"/></label>{editor.kind==='position'&&<label className="block text-sm font-medium mt-5">Departamento<select value={editor.value.department_id??''} onChange={e=>setEditor({kind:'position',value:{...editor.value,department_id:e.target.value||null}})} className="mt-2 w-full rounded-xl border bg-white px-4 py-3"><option value="">Sin departamento</option>{departments.map(d=><option key={d.id} value={d.id}>{d.name}</option>)}</select></label>}<label className="block text-sm font-medium mt-5">Descripción<textarea value={editor.value.description??''} onChange={e=>setEditor({...editor,value:{...editor.value,description:e.target.value}} as Editor)} className="mt-2 w-full rounded-xl border px-4 py-3 min-h-28"/></label><div className="flex justify-end gap-3 mt-8"><button onClick={()=>setEditor(null)} className="px-5 py-3 font-semibold">Cancelar</button><button onClick={persist} className="rounded-xl bg-[#244e3d] text-white px-5 py-3 font-semibold">Guardar</button></div></div></div>}
  </SettingsLayout>
}
