import { useEffect, useState, type FormEvent } from 'react'
import type React from 'react'
import { CheckCircle2, Copy, KeyRound, UserPlus, X } from 'lucide-react'
import { getCompanyMembers, getRestaurants, getRoles, updateCompanyMember } from '../../services/settings-data'
import { createInvitation, getInvitations, type InvitationRecord } from '../../services/invitations-data'
import type { CompanyMemberRecord, RestaurantRecord, RoleRecord } from '../../types/domain'
import { SettingsLayout } from './SettingsLayout'

export function UsersSettings(){
 const[members,setMembers]=useState<CompanyMemberRecord[]>([]),[roles,setRoles]=useState<RoleRecord[]>([]),[restaurants,setRestaurants]=useState<RestaurantRecord[]>([]),[invitations,setInvitations]=useState<InvitationRecord[]>([])
 const[editing,setEditing]=useState<CompanyMemberRecord|null>(null),[inviting,setInviting]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[link,setLink]=useState('')
 const[form,setForm]=useState({email:'',firstName:'',lastName:'',roleId:'',restaurantId:''})
 const load=async()=>{const[m,r,rs,i]=await Promise.all([getCompanyMembers(),getRoles(),getRestaurants(),getInvitations()]);setMembers(m);setRoles(r);setRestaurants(rs);setInvitations(i);setForm(v=>({...v,roleId:v.roleId||r[0]?.id||'',restaurantId:v.restaurantId||rs[0]?.id||''}))}
 useEffect(()=>{load().catch(e=>setMessage(e.message))},[])
 const name=(m:CompanyMemberRecord)=>[m.profile?.first_name,m.profile?.last_name].filter(Boolean).join(' ')||'Usuario sin perfil'
 const invite=async(e:FormEvent)=>{e.preventDefault();setBusy(true);try{const result=await createInvitation(form);setLink(`${location.origin}/aceptar-invitacion?token=${result.token}`);setMessage('Invitación creada correctamente.');await load()}catch(error){setMessage(error instanceof Error?error.message:'No se pudo crear la invitación')}finally{setBusy(false)}}
 const save=async()=>{if(!editing)return;await updateCompanyMember(editing.id,{role_id:editing.role_id});setEditing(null);setMessage('Rol actualizado.');await load()}
 return <SettingsLayout eyebrow="Accesos" title="Usuarios" description="Controla quién puede entrar en la empresa y qué responsabilidad tiene.">
  <div className="rounded-2xl border border-[#efd9c7] bg-[#fff7f0] p-5 mb-6 flex flex-wrap items-center gap-4"><span className="h-11 w-11 rounded-xl bg-white text-[#b95d2e] grid place-items-center"><KeyRound size={21}/></span><div className="flex-1 min-w-60"><p className="font-semibold">Invitaciones seguras</p><p className="text-sm text-[#756b64] mt-1">Cada enlace es privado, caduca en 7 días y solo funciona con el correo invitado.</p></div><button onClick={()=>{setInviting(true);setLink('')}} className="inline-flex items-center gap-2 rounded-xl bg-[#173c2e] text-white px-4 py-3 font-semibold"><UserPlus size={18}/>Invitar usuario</button></div>
  {message&&<p className="mb-4 text-sm text-[#466052] inline-flex items-center gap-2"><CheckCircle2 size={16}/>{message}</p>}
  <section className="card overflow-hidden"><header className="px-6 py-4 border-b flex justify-between"><h2 className="font-semibold">Miembros de la empresa</h2><span className="text-sm text-[#78827d]">{members.length} usuarios</span></header><div className="divide-y">{members.map(m=><button key={m.id} onClick={()=>setEditing(m)} className="w-full p-5 flex items-center gap-4 text-left hover:bg-[#f8faf8]"><span className="h-11 w-11 rounded-full bg-[#d97840] text-white grid place-items-center font-semibold">{name(m)[0]}</span><div className="flex-1"><p className="font-semibold">{name(m)}</p><p className="text-xs text-[#89928e]">ID {m.user_id.slice(0,8)}…</p></div><span>{m.role?.name??'Sin rol'}</span><span className="text-xs rounded-full px-3 py-1 bg-[#e5f0e9] text-[#2e6b50]">Activo</span></button>)}</div></section>
  {invitations.length>0&&<section className="card overflow-hidden mt-5"><header className="px-6 py-4 border-b"><h2 className="font-semibold">Invitaciones</h2></header><div className="divide-y">{invitations.map(i=><div key={i.id} className="p-5 flex flex-wrap items-center gap-4"><div className="flex-1"><p className="font-medium">{i.first_name} {i.last_name}</p><p className="text-sm text-[#78827d]">{i.email}</p></div><span>{i.role?.name}</span><span className="text-xs rounded-full px-3 py-1 bg-[#fff0e5] text-[#a65128]">{i.status==='pending'?'Pendiente':i.status}</span></div>)}</div></section>}
  {inviting&&<Drawer close={()=>setInviting(false)} title="Invitar usuario">{link?<div className="mt-8"><p className="font-semibold">Invitación preparada</p><p className="text-sm text-[#68736d] mt-2">Compártela únicamente con {form.firstName}. Deberá entrar usando {form.email}.</p><div className="mt-5 rounded-xl bg-[#eef3ef] p-4 text-sm break-all">{link}</div><button onClick={async()=>{await navigator.clipboard.writeText(link);setMessage('Enlace copiado.')}} className="mt-4 w-full rounded-xl bg-[#173c2e] text-white p-3 font-semibold"><Copy size={18} className="inline mr-2"/>Copiar enlace</button></div>:<form onSubmit={invite} className="mt-8 space-y-4"><div className="grid grid-cols-2 gap-4"><Field label="Nombre" value={form.firstName} set={v=>setForm({...form,firstName:v})}/><Field label="Apellidos" value={form.lastName} set={v=>setForm({...form,lastName:v})}/></div><Field label="Correo electrónico" value={form.email} set={v=>setForm({...form,email:v})} email/><Select label="Rol" value={form.roleId} set={v=>setForm({...form,roleId:v})} options={roles.map(r=>[r.id,r.name])}/><Select label="Restaurante" value={form.restaurantId} set={v=>setForm({...form,restaurantId:v})} options={[['','Todos los restaurantes'],...restaurants.map(r=>[r.id,r.name])]}/><button disabled={busy} className="w-full rounded-xl bg-[#173c2e] text-white p-3 font-semibold disabled:opacity-50">{busy?'Creando…':'Crear invitación segura'}</button></form>}</Drawer>}
  {editing&&<Drawer close={()=>setEditing(null)} title={name(editing)}><div className="mt-8"><Select label="Rol" value={editing.role_id} set={v=>setEditing({...editing,role_id:v})} options={roles.map(r=>[r.id,r.name])}/><button onClick={save} className="mt-6 w-full rounded-xl bg-[#173c2e] text-white p-3 font-semibold">Guardar rol</button></div></Drawer>}
 </SettingsLayout>
}
function Drawer({close,title,children}:{close:()=>void;title:string;children:React.ReactNode}){return <div className="fixed inset-0 bg-[#183128]/35 z-50 flex justify-end" onMouseDown={close}><div className="w-full max-w-lg h-full overflow-y-auto bg-[#fbfcfa] shadow-2xl p-7" onMouseDown={e=>e.stopPropagation()}><div className="flex justify-between"><div><p className="text-sm text-[#bd622f] font-semibold">Acceso</p><h2 className="text-2xl font-semibold mt-1">{title}</h2></div><button onClick={close}><X/></button></div>{children}</div></div>}
function Field({label,value,set,email=false}:{label:string;value:string;set:(v:string)=>void;email?:boolean}){return <label className="block text-sm font-medium">{label}<input required type={email?'email':'text'} value={value} onChange={e=>set(e.target.value)} className="mt-2 w-full rounded-xl border bg-white px-4 py-3"/></label>}
function Select({label,value,set,options}:{label:string;value:string;set:(v:string)=>void;options:string[][]}){return <label className="block text-sm font-medium">{label}<select required value={value} onChange={e=>set(e.target.value)} className="mt-2 w-full rounded-xl border bg-white px-4 py-3">{options.map(([id,n])=><option key={id} value={id}>{n}</option>)}</select></label>}

