import { useEffect, useState } from 'react'
import { CheckCircle2, KeyRound, UserPlus, UsersRound, X } from 'lucide-react'
import { getCompanyMembers, getRoles, updateCompanyMember } from '../../services/settings-data'
import type { CompanyMemberRecord, RoleRecord } from '../../types/domain'
import { SettingsLayout } from './SettingsLayout'

export function UsersSettings() {
  const [members,setMembers]=useState<CompanyMemberRecord[]>([])
  const [roles,setRoles]=useState<RoleRecord[]>([])
  const [editing,setEditing]=useState<CompanyMemberRecord|null>(null)
  const [message,setMessage]=useState('')
  const load=async()=>{const [memberRows,roleRows]=await Promise.all([getCompanyMembers(),getRoles()]);setMembers(memberRows);setRoles(roleRows)}
  useEffect(()=>{load().catch(e=>setMessage(e.message))},[])
  const displayName=(member:CompanyMemberRecord)=>[member.profile?.first_name,member.profile?.last_name].filter(Boolean).join(' ')||'Usuario sin perfil'
  const initials=(member:CompanyMemberRecord)=>displayName(member).split(' ').slice(0,2).map(word=>word[0]).join('').toUpperCase()
  const save=async()=>{if(!editing)return;try{await updateCompanyMember(editing.id,{role_id:editing.role_id});setEditing(null);setMessage('Rol actualizado correctamente.');await load()}catch(e){setMessage(e instanceof Error?e.message:'No se pudo actualizar el rol.')}}
  return <SettingsLayout eyebrow="Accesos" title="Usuarios" description="Controla quién puede entrar en la empresa y qué responsabilidad tiene.">
    <div className="rounded-2xl border border-[#efd9c7] bg-[#fff7f0] p-5 mb-6 flex flex-wrap items-center gap-4"><span className="h-11 w-11 rounded-xl bg-white text-[#b95d2e] grid place-items-center"><KeyRound size={21}/></span><div className="flex-1 min-w-60"><p className="font-semibold">Invitaciones seguras</p><p className="text-sm text-[#756b64] mt-1">Se activarán mediante una función privada de Supabase. Ninguna clave administrativa quedará expuesta en la app.</p></div><button disabled className="inline-flex items-center gap-2 rounded-xl bg-[#eadfd7] text-[#8b7668] px-4 py-3 font-semibold cursor-not-allowed"><UserPlus size={18}/> Invitar usuario</button></div>
    {message&&<p className="mb-4 text-sm text-[#466052] inline-flex items-center gap-2"><CheckCircle2 size={16}/>{message}</p>}
    <div className="card overflow-hidden"><div className="px-6 py-4 border-b border-[#e6ebe7] flex items-center justify-between"><h2 className="font-semibold">Miembros de la empresa</h2><span className="text-sm text-[#78827d]">{members.length} {members.length===1?'usuario':'usuarios'}</span></div>{members.length===0?<p className="p-8 text-[#75807a]">No se han encontrado usuarios accesibles.</p>:<div className="divide-y divide-[#edf0ed]">{members.map(member=><button key={member.id} onClick={()=>setEditing(member)} className="w-full p-5 flex flex-wrap items-center gap-4 text-left hover:bg-[#f8faf8]"><span className="h-11 w-11 rounded-full bg-[#d97840] text-white grid place-items-center font-semibold">{initials(member)}</span><div className="min-w-52 flex-1"><p className="font-semibold">{displayName(member)}</p><p className="text-xs text-[#89928e] mt-1">ID {member.user_id.slice(0,8)}…</p></div><span className="text-sm font-medium w-36">{member.role?.name??'Sin rol'}</span><span className={`text-xs font-semibold rounded-full px-3 py-1 ${member.active?'bg-[#e5f0e9] text-[#2e6b50]':'bg-[#eceeed] text-[#747c77]'}`}>{member.active?'Activo':'Suspendido'}</span></button>)}</div>}</div>
    {editing&&<div className="fixed inset-0 bg-[#183128]/35 z-50 flex justify-end" onMouseDown={()=>setEditing(null)}><div className="w-full max-w-lg h-full bg-[#fbfcfa] shadow-2xl p-7" onMouseDown={e=>e.stopPropagation()}><div className="flex justify-between"><div><p className="text-sm text-[#bd622f] font-semibold">Acceso de usuario</p><h2 className="text-2xl font-semibold mt-1">{displayName(editing)}</h2></div><button onClick={()=>setEditing(null)} aria-label="Cerrar" className="p-2"><X/></button></div><label className="block text-sm font-medium mt-8">Rol<select value={editing.role_id} onChange={e=>setEditing({...editing,role_id:e.target.value})} className="mt-2 w-full rounded-xl border border-[#dce3de] bg-white px-4 py-3">{roles.map(role=><option key={role.id} value={role.id}>{role.name}</option>)}</select></label><div className="rounded-xl bg-[#eef3ef] p-4 mt-7 text-sm text-[#607068]"><UsersRound size={18} className="mb-2"/>El rol se aplica a toda la empresa. La suspensión de acceso y el alcance por restaurante se añadirán con la próxima ampliación segura de la base de datos.</div><div className="flex justify-end gap-3 mt-8"><button onClick={()=>setEditing(null)} className="px-5 py-3 font-semibold">Cancelar</button><button onClick={save} className="rounded-xl bg-[#244e3d] text-white px-5 py-3 font-semibold">Guardar rol</button></div></div></div>}
  </SettingsLayout>
}
