import { useEffect, useMemo, useState } from 'react'
import { ChevronLeft, ChevronRight, Plus, Send, X } from 'lucide-react'
import { ensureSchedulePeriod, getEmployees, getSchedulePeriod, getWeekShifts, publishSchedulePeriod, saveShift } from '../../services/restaurant-data'
import { getDepartments, getPositions, getRestaurants } from '../../services/settings-data'
import type { DepartmentRecord, EmployeeRecord, PositionRecord, SchedulePeriodRecord, ShiftRecord } from '../../types/domain'

const iso=(date:Date)=>date.toISOString().slice(0,10);const addDays=(date:Date,days:number)=>{const copy=new Date(date);copy.setDate(copy.getDate()+days);return copy}

export function ScheduleManagement(){
  const [weekStart,setWeekStart]=useState(new Date('2026-09-07T12:00:00'));const [employees,setEmployees]=useState<EmployeeRecord[]>([]);const [shifts,setShifts]=useState<ShiftRecord[]>([]);const [departments,setDepartments]=useState<DepartmentRecord[]>([]);const [positions,setPositions]=useState<PositionRecord[]>([]);const [restaurantId,setRestaurantId]=useState('');const [period,setPeriod]=useState<SchedulePeriodRecord|null>(null);const [editing,setEditing]=useState<ShiftRecord|null>(null);const [message,setMessage]=useState('')
  const days=useMemo(()=>Array.from({length:7},(_,i)=>addDays(weekStart,i)),[weekStart]);const start=iso(weekStart),end=iso(days[6])
  const load=async()=>{const [team,depts,jobs,restaurants]=await Promise.all([getEmployees(),getDepartments(),getPositions(),getRestaurants()]);const localId=restaurantId||restaurants[0]?.id||'';setRestaurantId(localId);setEmployees(team);setDepartments(depts);setPositions(jobs);if(localId){const [rows,schedule]=await Promise.all([getWeekShifts(start,end),getSchedulePeriod(localId,start,end)]);setShifts(rows);setPeriod(schedule)}}
  useEffect(()=>{load().catch(e=>setMessage(e.message))},[start])
  const openNew=async(date:string)=>{if(!restaurantId)return;const schedule=period??await ensureSchedulePeriod(restaurantId,start,end);setPeriod(schedule);setEditing({id:'',schedule_period_id:schedule.id,restaurant_id:restaurantId,employee_id:employees[0]?.id??'',shift_date:date,start_time:'10:00',end_time:'18:00',break_minutes:0,status:'scheduled',department_id:employees[0]?.department_id??null,position_id:employees[0]?.position_id??null,departments:null,employees:null})}
  const persist=async()=>{if(!editing?.employee_id)return;try{await saveShift(editing as ShiftRecord&Required<Pick<ShiftRecord,'schedule_period_id'|'restaurant_id'>>);setEditing(null);setMessage('Turno guardado correctamente.');await load()}catch(e){setMessage(e instanceof Error?e.message:'No se pudo guardar el turno.')}}
  const publish=async()=>{if(!period)return setMessage('Crea al menos un turno antes de publicar.');try{await publishSchedulePeriod(period.id);setMessage('Horario publicado correctamente.');await load()}catch(e){setMessage(e instanceof Error?e.message:'No se pudo publicar.')}}
  return <div className="fade-in"><div className="flex flex-wrap items-end justify-between gap-4 mb-7"><div><p className="text-sm text-[#bd622f] font-semibold">Planificación</p><h1 className="text-3xl font-semibold mt-1">Horario semanal</h1><p className="text-[#6e7873] mt-2">{days[0].toLocaleDateString('es-ES',{day:'numeric',month:'long'})} – {days[6].toLocaleDateString('es-ES',{day:'numeric',month:'long',year:'numeric'})}</p></div><div className="flex gap-2"><button onClick={()=>setWeekStart(addDays(weekStart,-7))} className="h-11 w-11 rounded-xl border bg-white grid place-items-center"><ChevronLeft/></button><button onClick={()=>setWeekStart(addDays(weekStart,7))} className="h-11 w-11 rounded-xl border bg-white grid place-items-center"><ChevronRight/></button><button onClick={()=>openNew(start)} className="h-11 px-4 rounded-xl bg-[#173c2e] text-white font-semibold flex items-center gap-2"><Plus size={17}/> Turno</button><button onClick={publish} className="h-11 px-4 rounded-xl bg-[#d97840] text-white font-semibold flex items-center gap-2"><Send size={17}/> Publicar</button></div></div>
  {message&&<p className="mb-4 text-sm text-[#4f6659]">{message}</p>}<div className="card overflow-x-auto"><div className="min-w-[1050px]"><div className="grid grid-cols-[190px_repeat(7,1fr)] bg-[#f8f9f7] border-b"><div className="p-4 font-semibold">Empleado</div>{days.map(day=><div key={iso(day)} className="p-4 text-center text-sm font-semibold capitalize">{day.toLocaleDateString('es-ES',{weekday:'short',day:'numeric'})}</div>)}</div>{employees.map(employee=><div key={employee.id} className="grid grid-cols-[190px_repeat(7,1fr)] min-h-28 border-b last:border-0"><div className="p-4"><p className="font-semibold">{employee.first_name} {employee.last_name}</p><p className="text-xs text-[#7d8782] mt-1">{employee.positions?.name||'Sin puesto'}</p></div>{days.map(day=>{const date=iso(day);const rows=shifts.filter(s=>s.employee_id===employee.id&&s.shift_date===date);return <button key={date} onClick={()=>rows[0]?setEditing(rows[0]):openNew(date)} className="border-l p-2 text-left hover:bg-[#fafbf9]">{rows.map(row=><div key={row.id} className="rounded-lg bg-[#e4efe8] border-l-[3px] border-[#397158] p-2 mb-1"><p className="text-xs font-semibold text-[#28543f]">{row.start_time.slice(0,5)}–{row.end_time.slice(0,5)}</p><p className="text-[11px] text-[#668071] mt-1">{row.departments?.name||'Turno'}</p></div>)}</button>})}</div>)}</div></div><div className="mt-4 flex gap-5 text-sm"><span><b>{shifts.length}</b> turnos</span><span className="ml-auto font-semibold text-[#397158]">{period?.status==='published'?'Publicado':'Borrador'}</span></div>
  {editing&&<div className="fixed inset-0 bg-[#183128]/35 z-50 flex justify-end" onMouseDown={()=>setEditing(null)}><div className="w-full max-w-lg h-full bg-[#fbfcfa] p-7" onMouseDown={e=>e.stopPropagation()}><div className="flex justify-between"><h2 className="text-2xl font-semibold">{editing.id?'Editar turno':'Nuevo turno'}</h2><button onClick={()=>setEditing(null)}><X/></button></div><div className="grid gap-4 mt-8"><label className="text-sm font-medium">Empleado<select value={editing.employee_id} onChange={e=>{const employee=employees.find(x=>x.id===e.target.value);setEditing({...editing,employee_id:e.target.value,department_id:employee?.department_id??null,position_id:employee?.position_id??null})}} className="mt-2 w-full rounded-xl border bg-white px-4 py-3">{employees.map(e=><option key={e.id} value={e.id}>{e.first_name} {e.last_name}</option>)}</select></label><label className="text-sm font-medium">Fecha<input type="date" value={editing.shift_date} onChange={e=>setEditing({...editing,shift_date:e.target.value})} className="mt-2 w-full rounded-xl border px-4 py-3"/></label><div className="grid grid-cols-2 gap-4"><label className="text-sm font-medium">Inicio<input type="time" value={editing.start_time.slice(0,5)} onChange={e=>setEditing({...editing,start_time:e.target.value})} className="mt-2 w-full rounded-xl border px-4 py-3"/></label><label className="text-sm font-medium">Fin<input type="time" value={editing.end_time.slice(0,5)} onChange={e=>setEditing({...editing,end_time:e.target.value})} className="mt-2 w-full rounded-xl border px-4 py-3"/></label></div><label className="text-sm font-medium">Departamento<select value={editing.department_id??''} onChange={e=>setEditing({...editing,department_id:e.target.value||null})} className="mt-2 w-full rounded-xl border bg-white px-4 py-3"><option value="">Sin departamento</option>{departments.map(d=><option key={d.id} value={d.id}>{d.name}</option>)}</select></label><label className="text-sm font-medium">Puesto<select value={editing.position_id??''} onChange={e=>setEditing({...editing,position_id:e.target.value||null})} className="mt-2 w-full rounded-xl border bg-white px-4 py-3"><option value="">Sin puesto</option>{positions.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label></div><div className="flex justify-end gap-3 mt-8"><button onClick={()=>setEditing(null)} className="px-5 py-3 font-semibold">Cancelar</button><button onClick={persist} className="rounded-xl bg-[#244e3d] text-white px-5 py-3 font-semibold">Guardar turno</button></div></div></div>}
  </div>
}
