import { useEffect, useState } from 'react'
import { Clock3, Plus, X } from 'lucide-react'
import { getEmployees, getTimeEntries, saveTimeEntry } from '../../services/restaurant-data'
import { getRestaurants } from '../../services/settings-data'
import type { EmployeeRecord, RestaurantRecord, TimeEntryRecord } from '../../types/domain'

const localDateTime=(value:string|null)=>value?new Date(value).toISOString().slice(0,16):''

export function TimeTracking(){
  const [entries,setEntries]=useState<TimeEntryRecord[]>([]);const [employees,setEmployees]=useState<EmployeeRecord[]>([]);const [restaurants,setRestaurants]=useState<RestaurantRecord[]>([]);const [editing,setEditing]=useState<TimeEntryRecord|null>(null);const [message,setMessage]=useState('')
  const load=async()=>{const [rows,team,locals]=await Promise.all([getTimeEntries(),getEmployees(),getRestaurants()]);setEntries(rows);setEmployees(team);setRestaurants(locals)}
  useEffect(()=>{load().catch(e=>setMessage(e.message))},[])
  const create=()=>setEditing({id:'',employee_id:employees[0]?.id??'',restaurant_id:restaurants[0]?.id??'',shift_id:null,clock_in:new Date().toISOString(),clock_out:null,break_minutes:0,source:'manager',status:'completed',notes:'',employees:null})
  const save=async()=>{if(!editing?.employee_id||!editing.restaurant_id)return setMessage('Selecciona empleado y restaurante.');try{await saveTimeEntry(editing);setEditing(null);setMessage('Fichaje guardado correctamente.');await load()}catch(e){setMessage(e instanceof Error?e.message:'No se pudo guardar el fichaje.')}}
  return <div className="fade-in"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm text-[#bd622f] font-semibold">Personal</p><h1 className="text-3xl font-semibold mt-1">Fichajes</h1><p className="text-[#6e7873] mt-3">Entradas, salidas y correcciones de jornada del equipo.</p></div><button onClick={create} className="h-11 px-4 rounded-xl bg-[#173c2e] text-white font-semibold flex items-center gap-2"><Plus size={17}/> Fichaje manual</button></div>
  {message&&<p className="mt-5 text-sm text-[#52675b]">{message}</p>}<div className="grid sm:grid-cols-3 gap-4 mt-7"><div className="card p-5"><p className="text-sm text-[#76817b]">Registros</p><p className="text-3xl font-semibold mt-2">{entries.length}</p></div><div className="card p-5"><p className="text-sm text-[#76817b]">Jornadas abiertas</p><p className="text-3xl font-semibold mt-2">{entries.filter(e=>!e.clock_out).length}</p></div><div className="card p-5"><p className="text-sm text-[#76817b]">A revisar</p><p className="text-3xl font-semibold mt-2">{entries.filter(e=>e.status!=='completed').length}</p></div></div>
  <div className="card overflow-hidden mt-5"><div className="p-5 border-b flex items-center gap-3"><Clock3 className="text-[#397158]"/><h2 className="font-semibold">Historial reciente</h2></div>{entries.length===0?<p className="p-8 text-[#748079]">No hay fichajes registrados.</p>:<div className="divide-y">{entries.map(entry=><button key={entry.id} onClick={()=>setEditing(entry)} className="p-5 w-full flex flex-wrap items-center gap-4 text-left hover:bg-[#f8faf8]"><div className="min-w-52 flex-1"><p className="font-semibold">{entry.employees?.first_name} {entry.employees?.last_name}</p><p className="text-sm text-[#7c8681] mt-1">{new Date(entry.clock_in).toLocaleDateString('es-ES')}</p></div><div><p className="text-sm font-medium">{new Date(entry.clock_in).toLocaleTimeString('es-ES',{hour:'2-digit',minute:'2-digit'})} → {entry.clock_out?new Date(entry.clock_out).toLocaleTimeString('es-ES',{hour:'2-digit',minute:'2-digit'}):'En curso'}</p><p className="text-xs text-[#89928e] mt-1">Descanso: {entry.break_minutes} min · {entry.source}</p></div><span className={`text-xs font-semibold rounded-full px-3 py-1 ${entry.status==='completed'?'bg-[#e5f0e9] text-[#2e6b50]':'bg-[#fff0e4] text-[#a65128]'}`}>{entry.status}</span><span className="text-sm font-semibold text-[#315f4c]">Editar</span></button>)}</div>}</div>
  {editing&&<div className="fixed inset-0 bg-[#183128]/35 z-50 flex justify-end" onMouseDown={()=>setEditing(null)}><div className="w-full max-w-xl h-full bg-[#fbfcfa] shadow-2xl overflow-y-auto p-7" onMouseDown={e=>e.stopPropagation()}><div className="flex justify-between"><div><p className="text-sm text-[#bd622f] font-semibold">Control horario</p><h2 className="text-2xl font-semibold mt-1">{editing.id?'Corregir fichaje':'Fichaje manual'}</h2></div><button onClick={()=>setEditing(null)}><X/></button></div><div className="grid gap-4 mt-8"><label className="text-sm font-medium">Empleado<select value={editing.employee_id} onChange={e=>setEditing({...editing,employee_id:e.target.value})} className="mt-2 w-full rounded-xl border bg-white px-4 py-3">{employees.map(e=><option key={e.id} value={e.id}>{e.first_name} {e.last_name}</option>)}</select></label><label className="text-sm font-medium">Restaurante<select value={editing.restaurant_id} onChange={e=>setEditing({...editing,restaurant_id:e.target.value})} className="mt-2 w-full rounded-xl border bg-white px-4 py-3">{restaurants.map(r=><option key={r.id} value={r.id}>{r.name}</option>)}</select></label><div className="grid sm:grid-cols-2 gap-4"><label className="text-sm font-medium">Entrada<input type="datetime-local" value={localDateTime(editing.clock_in)} onChange={e=>setEditing({...editing,clock_in:e.target.value})} className="mt-2 w-full rounded-xl border px-4 py-3"/></label><label className="text-sm font-medium">Salida<input type="datetime-local" value={localDateTime(editing.clock_out)} onChange={e=>setEditing({...editing,clock_out:e.target.value||null})} className="mt-2 w-full rounded-xl border px-4 py-3"/></label></div><label className="text-sm font-medium">Descanso (minutos)<input type="number" min="0" value={editing.break_minutes} onChange={e=>setEditing({...editing,break_minutes:Number(e.target.value)})} className="mt-2 w-full rounded-xl border px-4 py-3"/></label><label className="text-sm font-medium">Estado<select value={editing.status} onChange={e=>setEditing({...editing,status:e.target.value})} className="mt-2 w-full rounded-xl border bg-white px-4 py-3"><option value="completed">Completado</option><option value="open">Abierto</option><option value="pending_review">Revisar</option><option value="corrected">Corregido</option></select></label><label className="text-sm font-medium">Notas<textarea value={editing.notes??''} onChange={e=>setEditing({...editing,notes:e.target.value})} className="mt-2 w-full rounded-xl border px-4 py-3 min-h-24"/></label></div><div className="flex justify-end gap-3 mt-8"><button onClick={()=>setEditing(null)} className="px-5 py-3 font-semibold">Cancelar</button><button onClick={save} className="rounded-xl bg-[#244e3d] text-white px-5 py-3 font-semibold">Guardar fichaje</button></div></div></div>}
  </div>
}
