import { useEffect, useState, type ReactNode } from 'react'
import { Banknote, Calculator, CheckCircle2, CircleDollarSign, Plus, Receipt, Scale, X } from 'lucide-react'
import { getCompany, getRestaurants } from '../../services/settings-data'
import { getCashData, saveCash, type CashMovement, type CashRegister, type CashSession, type PaymentSummary } from '../../services/cash-data'

type Tab='overview'|'sessions'|'movements'|'payments'|'reconciliation'
type Editor={kind:'register'|'session'|'movement';value:Record<string,unknown>}
const tabs:[Tab,string][]=[['overview','Resumen'],['sessions','Turnos de caja'],['movements','Movimientos'],['payments','Cobros'],['reconciliation','Arqueo']]
const euro=(n:number)=>new Intl.NumberFormat('es-ES',{style:'currency',currency:'EUR'}).format(n)

export function CashHub(){
 const[tab,setTab]=useState<Tab>('overview'),[registers,setRegisters]=useState<CashRegister[]>([]),[sessions,setSessions]=useState<CashSession[]>([]),[movements,setMovements]=useState<CashMovement[]>([]),[payments,setPayments]=useState<PaymentSummary[]>([]),[ctx,setCtx]=useState({company_id:'',restaurant_id:''}),[editor,setEditor]=useState<Editor|null>(null),[message,setMessage]=useState('')
 const load=async()=>{const[d,c,r]=await Promise.all([getCashData(),getCompany(),getRestaurants()]);setRegisters(d.registers);setSessions(d.sessions);setMovements(d.movements);setPayments(d.payments);setCtx({company_id:c?.id??'',restaurant_id:r[0]?.id??''})}
 useEffect(()=>{load().catch(e=>setMessage(String(e.message).includes('does not exist')?'Activa primero el bloque Caja en Supabase.':e.message))},[])
 const create=()=>{if(tab==='sessions')setEditor({kind:registers.length?'session':'register',value:registers.length?{register_id:registers[0].id,opening_float:150,status:'open',business_date:new Date().toISOString().slice(0,10)}:{name:'Caja principal',code:`CAJA-${registers.length+1}`,location:'Barra',active:true}});if(tab==='movements')setEditor({kind:'movement',value:{session_id:sessions[0]?.id??'',movement_type:'cash_out',amount:0,description:''}});if(tab==='payments')setMessage('Los cobros se incorporan automáticamente desde el TPV o el cierre de caja.')}
 const save=async()=>{if(!editor)return;try{const table=editor.kind==='register'?'cash_registers':editor.kind==='session'?'cash_sessions':'cash_movements';await saveCash(table,{...editor.value,...ctx});setEditor(null);setMessage('Guardado correctamente.');await load()}catch(e){setMessage(e instanceof Error?e.message:'No se pudo guardar.')}}
 const open=sessions.filter(s=>s.status==='open'),cashIn=movements.filter(m=>m.movement_type==='cash_in').reduce((s,m)=>s+Number(m.amount),0),cashOut=movements.filter(m=>['cash_out','refund'].includes(m.movement_type)).reduce((s,m)=>s+Math.abs(Number(m.amount)),0),sales=payments.reduce((s,p)=>s+Number(p.amount),0),difference=sessions.reduce((s,x)=>s+Number(x.difference??0),0)
 return <div className="fade-in"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm text-[#bd622f] font-semibold">Caja y cierres</p><h1 className="text-3xl font-semibold mt-1">Control de caja</h1><p className="text-[#6e7873] mt-3">Aperturas, cobros, movimientos y arqueos con trazabilidad diaria.</p></div>{['sessions','movements'].includes(tab)&&<button onClick={create} className="h-11 px-4 rounded-xl bg-[#173c2e] text-white font-semibold flex items-center gap-2"><Plus size={17}/>Añadir</button>}</div>
 <div className="flex gap-2 mt-7 overflow-x-auto pb-2">{tabs.map(([k,l])=><button key={k} onClick={()=>setTab(k)} className={`whitespace-nowrap rounded-xl px-4 py-2.5 text-sm font-semibold ${tab===k?'bg-[#173c2e] text-white':'bg-white border text-[#52645b]'}`}>{l}</button>)}</div>{message&&<p className="mt-4 rounded-xl bg-[#fff7f0] border border-[#efd9c7] p-4 text-sm">{message}</p>}
 {tab==='overview'&&<><div className="grid sm:grid-cols-2 xl:grid-cols-4 gap-4 mt-6"><Metric l="Ventas registradas" v={euro(sales)} n={`${payments.reduce((s,p)=>s+p.transaction_count,0)} operaciones`} i={<CircleDollarSign/>}/><Metric l="Cajas abiertas" v={open.length} n={`${registers.length} cajas configuradas`} i={<Banknote/>}/><Metric l="Entradas / salidas" v={`${euro(cashIn)} / ${euro(cashOut)}`} n="Movimientos manuales" i={<Receipt/>}/><Metric l="Diferencia" v={euro(difference)} n={Math.abs(difference)<1?'Arqueos cuadrados':'Requiere revisión'} i={<Scale/>}/></div><List>{registers.map(r=>{const s=sessions.find(x=>x.register_id===r.id&&x.status==='open');return <Row key={r.id} title={r.name} meta={s?`Abierta · fondo ${euro(Number(s.opening_float))}`:`${r.location??'Sin ubicación'} · cerrada`} badge={s?'Abierta':'Cerrada'}/>} )}</List></>}
 {tab==='sessions'&&<List>{sessions.map(s=><Row key={s.id} title={`${relationName(s.cash_registers)} · ${new Date(s.opened_at).toLocaleDateString('es-ES')}`} meta={`Fondo inicial ${euro(Number(s.opening_float))}`} badge={s.status}/>)}</List>}
 {tab==='movements'&&<List>{movements.map(m=><Row key={m.id} title={m.description??'Movimiento de caja'} meta={`${m.movement_type} · ${new Date(m.created_at).toLocaleString('es-ES')}`} badge={euro(Number(m.amount))}/>)}</List>}
 {tab==='payments'&&<List>{payments.map(p=><Row key={p.id} title={relationName(p.payment_methods)} meta={`${p.business_date} · ${p.transaction_count} operaciones`} badge={euro(Number(p.amount))}/>)}</List>}
 {tab==='reconciliation'&&<div className="grid lg:grid-cols-[1.2fr_.8fr] gap-5 mt-5"><section className="card p-6"><h2 className="font-semibold text-lg">Arqueos y diferencias</h2><p className="text-sm text-[#758079] mt-3">El sistema conserva el efectivo esperado, contado y cualquier diferencia de cada cierre.</p></section><section className="card p-6"><Calculator className="text-[#d16d38]"/><h2 className="font-semibold text-lg mt-5">Control activo</h2><div className="mt-5 rounded-xl bg-[#e8f1eb] p-4 flex gap-3"><CheckCircle2 className="text-[#2f6a54]"/><span className="text-sm font-semibold">Trazabilidad por usuario y caja</span></div></section></div>}
 {editor&&<Drawer editor={editor} registers={registers} sessions={sessions} setEditor={setEditor} save={save}/>}</div>
}
const relationName=(v:{name:string}|{name:string}[]|null|undefined)=>Array.isArray(v)?v[0]?.name??'Sin nombre':v?.name??'Sin nombre'
function Metric({l,v,n,i}:{l:string;v:string|number;n:string;i:ReactNode}){return <div className="card p-5"><span className="text-[#d16d38]">{i}</span><p className="text-sm text-[#758079] mt-4">{l}</p><p className="text-2xl font-semibold mt-1">{v}</p><p className="text-xs text-[#84908a] mt-2">{n}</p></div>}
function List({children}:{children:ReactNode}){return <div className="card divide-y mt-5 overflow-hidden">{children}</div>}
function Row({title,meta,badge}:{title:string;meta:string;badge:string}){return <div className="p-5 flex flex-wrap items-center gap-4"><div className="flex-1"><p className="font-semibold">{title}</p><p className="text-sm text-[#7a8580] mt-1">{meta}</p></div><span className="rounded-full bg-[#e8f1eb] px-3 py-1 text-xs font-semibold">{badge}</span></div>}
function Drawer({editor,registers,sessions,setEditor,save}:{editor:Editor;registers:CashRegister[];sessions:CashSession[];setEditor:(v:Editor|null)=>void;save:()=>void}){const v=editor.value,u=(k:string,x:string|number)=>setEditor({...editor,value:{...v,[k]:x}});return <div className="fixed inset-0 bg-[#183128]/35 z-50 flex justify-end" onMouseDown={()=>setEditor(null)}><div className="w-full max-w-xl h-full bg-[#fbfcfa] p-7" onMouseDown={e=>e.stopPropagation()}><div className="flex justify-between"><h2 className="text-2xl font-semibold">Nuevo registro</h2><button onClick={()=>setEditor(null)}><X/></button></div><div className="grid gap-4 mt-8">{editor.kind==='register'&&<><Field l="Nombre de caja" k="name" v={v.name} u={u}/><Field l="Código" k="code" v={v.code} u={u}/><Field l="Ubicación" k="location" v={v.location} u={u}/></>}{editor.kind==='session'&&<><Select l="Caja" k="register_id" v={v.register_id} u={u} rows={registers.map(r=>[r.id,r.name])}/><Field l="Fondo inicial" k="opening_float" v={v.opening_float} u={u} number/></>}{editor.kind==='movement'&&<><Select l="Turno de caja" k="session_id" v={v.session_id} u={u} rows={sessions.map(s=>[s.id,`${relationName(s.cash_registers)} · ${s.status}`])}/><Field l="Descripción" k="description" v={v.description} u={u}/><Field l="Importe" k="amount" v={v.amount} u={u} number/></>}</div><button onClick={save} className="mt-8 w-full rounded-xl bg-[#244e3d] text-white px-5 py-3 font-semibold">Guardar</button></div></div>}
function Field({l,k,v,u,number=false}:{l:string;k:string;v:unknown;u:(k:string,v:string|number)=>void;number?:boolean}){return <label className="text-sm font-medium">{l}<input type={number?'number':'text'} step={number?'0.01':undefined} value={String(v??'')} onChange={e=>u(k,number?Number(e.target.value):e.target.value)} className="mt-2 w-full rounded-xl border px-4 py-3"/></label>}
function Select({l,k,v,u,rows}:{l:string;k:string;v:unknown;u:(k:string,v:string)=>void;rows:string[][]}){return <label className="text-sm font-medium">{l}<select value={String(v??'')} onChange={e=>u(k,e.target.value)} className="mt-2 w-full rounded-xl border bg-white px-4 py-3">{rows.map(([id,n])=><option key={id} value={id}>{n}</option>)}</select></label>}
