import { useEffect, useState } from 'react'
import { AlertTriangle, CheckSquare2, ClipboardCheck, Plus, Settings2, Wrench, X } from 'lucide-react'
import { createChecklist, getOperationsData, saveOperation, type ChecklistRecord, type EquipmentRecord, type IncidentRecord, type TaskRecord } from '../../services/operations-data'
import { getCompany, getRestaurants } from '../../services/settings-data'

type Tab='today'|'tasks'|'checklists'|'incidents'|'equipment'
type Editor={kind:'task'|'incident'|'equipment'|'checklist';value:Record<string,unknown>}
const tabs:[Tab,string][]=[['today','Hoy'],['tasks','Tareas'],['checklists','Apertura y cierre'],['incidents','Incidencias'],['equipment','Mantenimiento']]

export function OperationsHub(){
  const [tab,setTab]=useState<Tab>('today');const [tasks,setTasks]=useState<TaskRecord[]>([]);const [incidents,setIncidents]=useState<IncidentRecord[]>([]);const [equipment,setEquipment]=useState<EquipmentRecord[]>([]);const [checklists,setChecklists]=useState<ChecklistRecord[]>([]);const [editor,setEditor]=useState<Editor|null>(null);const [context,setContext]=useState({company_id:'',restaurant_id:''});const [message,setMessage]=useState('')
  const load=async()=>{const [data,company,restaurants]=await Promise.all([getOperationsData(),getCompany(),getRestaurants()]);setTasks(data.tasks);setIncidents(data.incidents);setEquipment(data.equipment);setChecklists(data.checklists);setContext({company_id:company?.id??'',restaurant_id:restaurants[0]?.id??''})}
  useEffect(()=>{load().catch(error=>setMessage(error.message.includes('does not exist')?'Activa primero el bloque Operaciones en Supabase con la migración preparada.':error.message))},[])
  const startCreate=()=>{if(tab==='tasks')setEditor({kind:'task',value:{title:'',description:'',priority:'medium',category:'general',status:'pending'}});if(tab==='incidents')setEditor({kind:'incident',value:{title:'',description:'',priority:'medium',category:'operations',status:'new'}});if(tab==='equipment')setEditor({kind:'equipment',value:{name:'',category:'',location:'',status:'operational',next_maintenance_at:'',notes:''}});if(tab==='checklists')setEditor({kind:'checklist',value:{name:'',shift_type:'opening',items:''}})}
  const persist=async()=>{if(!editor)return;try{if(editor.kind==='checklist')await createChecklist({...context,name:String(editor.value.name??''),shift_type:String(editor.value.shift_type??'opening'),items:String(editor.value.items??'').split('\n')});else await saveOperation(editor.kind==='task'?'operational_tasks':editor.kind==='incident'?'incidents':'equipment',{...editor.value,...context});setEditor(null);setMessage('Guardado correctamente.');await load()}catch(error){setMessage(error instanceof Error?error.message:'No se pudo guardar.')}}
  const updateStatus=async(table:'operational_tasks'|'incidents',row:TaskRecord|IncidentRecord,status:string)=>{await saveOperation(table,{...row,status,...(status==='completed'?{completed_at:new Date().toISOString()}:{}),...(status==='resolved'?{resolved_at:new Date().toISOString()}: {})});await load()}
  const openTasks=tasks.filter(item=>item.status!=='completed'&&item.status!=='cancelled');const openIncidents=incidents.filter(item=>!['resolved','closed'].includes(item.status));const maintenanceDue=equipment.filter(item=>item.status!=='operational'||(item.next_maintenance_at&&item.next_maintenance_at<=new Date().toISOString().slice(0,10)))
  return <div className="fade-in"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm text-[#bd622f] font-semibold">Operaciones</p><h1 className="text-3xl font-semibold mt-1">Control diario del restaurante</h1><p className="text-[#6e7873] mt-3">Todo lo necesario para abrir, operar y cerrar el local sin perder información.</p></div>{tab!=='today'&&<button onClick={startCreate} className="h-11 px-4 rounded-xl bg-[#173c2e] text-white font-semibold flex items-center gap-2"><Plus size={17}/>Añadir</button>}</div>
  <div className="flex gap-2 mt-7 overflow-x-auto pb-2">{tabs.map(([key,label])=><button key={key} onClick={()=>setTab(key)} className={`whitespace-nowrap rounded-xl px-4 py-2.5 text-sm font-semibold ${tab===key?'bg-[#173c2e] text-white':'bg-white border text-[#52645b]'}`}>{label}</button>)}</div>{message&&<p className="mt-4 rounded-xl bg-[#fff7f0] border border-[#efd9c7] p-4 text-sm">{message}</p>}
  {tab==='today'&&<div><div className="grid sm:grid-cols-3 gap-4 mt-6"><Metric label="Tareas pendientes" value={openTasks.length} icon={<ClipboardCheck/>}/><Metric label="Incidencias abiertas" value={openIncidents.length} icon={<AlertTriangle/>}/><Metric label="Mantenimiento" value={maintenanceDue.length} icon={<Wrench/>}/></div><div className="grid lg:grid-cols-2 gap-5 mt-5"><Panel title="Prioridades de hoy">{openTasks.slice(0,5).map(item=><Row key={item.id} title={item.title} meta={`${item.priority} · ${item.status}`}/>)}</Panel><Panel title="Listas operativas">{checklists.map(item=><Row key={item.id} title={item.name} meta={`${item.checklist_items.length} pasos · ${item.shift_type}`}/>)}</Panel></div></div>}
  {tab==='tasks'&&<List>{tasks.map(item=><Row key={item.id} title={item.title} meta={`${item.category} · ${item.priority}`} badge={item.status} action={item.status!=='completed'?<button onClick={()=>void updateStatus('operational_tasks',item,'completed')} className="text-sm font-semibold text-[#2f6a50]">Completar</button>:undefined}/>)}</List>}
  {tab==='checklists'&&<List>{checklists.map(item=><Row key={item.id} title={item.name} meta={`${item.shift_type} · ${item.checklist_items.length} pasos`} badge={item.active?'Activa':'Inactiva'}/>)}</List>}
  {tab==='incidents'&&<List>{incidents.map(item=><Row key={item.id} title={item.title} meta={`${item.category} · ${item.priority}`} badge={item.status} action={!['resolved','closed'].includes(item.status)?<button onClick={()=>void updateStatus('incidents',item,'resolved')} className="text-sm font-semibold text-[#2f6a50]">Resolver</button>:undefined}/>)}</List>}
  {tab==='equipment'&&<List>{equipment.map(item=><Row key={item.id} title={item.name} meta={`${item.category||'Equipo'} · ${item.location||'Sin ubicación'}`} badge={item.status}/>)}</List>}
  {editor&&<EditorDrawer editor={editor} setEditor={setEditor} save={persist}/>}</div>
}

function Metric({label,value,icon}:{label:string;value:number;icon:React.ReactNode}){return <div className="card p-5 flex justify-between"><div><p className="text-sm text-[#758079]">{label}</p><p className="text-3xl font-semibold mt-2">{value}</p></div><span className="text-[#d16d38]">{icon}</span></div>}
function Panel({title,children}:{title:string;children:React.ReactNode}){return <section className="card overflow-hidden"><h2 className="font-semibold p-5 border-b">{title}</h2><div className="divide-y">{children||<p className="p-6 text-[#78827d]">Sin elementos pendientes.</p>}</div></section>}
function List({children}:{children:React.ReactNode}){return <div className="card divide-y mt-5 overflow-hidden">{children}</div>}
function Row({title,meta,badge,action}:{title:string;meta:string;badge?:string;action?:React.ReactNode}){return <div className="p-5 flex flex-wrap gap-4 items-center"><div className="flex-1 min-w-48"><p className="font-semibold">{title}</p><p className="text-sm text-[#7a8580] mt-1">{meta}</p></div>{badge&&<span className="rounded-full bg-[#edf3ef] px-3 py-1 text-xs font-semibold">{badge}</span>}{action}</div>}
function EditorDrawer({editor,setEditor,save}:{editor:Editor;setEditor:(value:Editor|null)=>void;save:()=>void}){const value=editor.value;const update=(key:string,next:string)=>setEditor({...editor,value:{...value,[key]:next}});const title=editor.kind==='task'?'Nueva tarea':editor.kind==='incident'?'Nueva incidencia':editor.kind==='equipment'?'Nuevo equipo':'Nueva lista';return <div className="fixed inset-0 bg-[#183128]/35 z-50 flex justify-end" onMouseDown={()=>setEditor(null)}><div className="w-full max-w-xl h-full bg-[#fbfcfa] p-7 overflow-y-auto" onMouseDown={event=>event.stopPropagation()}><div className="flex justify-between"><h2 className="text-2xl font-semibold">{title}</h2><button onClick={()=>setEditor(null)}><X/></button></div><div className="grid gap-4 mt-8"><Field label="Nombre" value={String(value.title??value.name??'')} onChange={next=>update(editor.kind==='equipment'||editor.kind==='checklist'?'name':'title',next)}/>{editor.kind!=='equipment'&&editor.kind!=='checklist'&&<Field label="Descripción" value={String(value.description??'')} onChange={next=>update('description',next)} area/>}{editor.kind==='checklist'&&<Field label="Pasos (uno por línea)" value={String(value.items??'')} onChange={next=>update('items',next)} area/>}<label className="text-sm font-medium">Tipo / categoría<select value={String(value.priority??value.shift_type??value.status??'')} onChange={event=>update(editor.kind==='checklist'?'shift_type':editor.kind==='equipment'?'status':'priority',event.target.value)} className="mt-2 w-full rounded-xl border bg-white px-4 py-3">{editor.kind==='checklist'?<><option value="opening">Apertura</option><option value="closing">Cierre</option><option value="service">Servicio</option></>:editor.kind==='equipment'?<><option value="operational">Operativo</option><option value="maintenance">En mantenimiento</option><option value="out_of_service">Fuera de servicio</option></>:<><option value="low">Baja</option><option value="medium">Media</option><option value="high">Alta</option><option value="critical">Crítica</option></>}</select></label>{editor.kind==='equipment'&&<><Field label="Categoría" value={String(value.category??'')} onChange={next=>update('category',next)}/><Field label="Ubicación" value={String(value.location??'')} onChange={next=>update('location',next)}/><Field label="Próximo mantenimiento" value={String(value.next_maintenance_at??'')} onChange={next=>update('next_maintenance_at',next)} type="date"/></>}</div><button onClick={save} className="mt-8 w-full rounded-xl bg-[#244e3d] text-white px-5 py-3 font-semibold">Guardar</button></div></div>}
function Field({label,value,onChange,area,type='text'}:{label:string;value:string;onChange:(value:string)=>void;area?:boolean;type?:string}){return <label className="text-sm font-medium">{label}{area?<textarea value={value} onChange={event=>onChange(event.target.value)} className="mt-2 w-full rounded-xl border px-4 py-3 min-h-28"/>:<input type={type} value={value} onChange={event=>onChange(event.target.value)} className="mt-2 w-full rounded-xl border px-4 py-3"/>}</label>}
