begin;
create table if not exists public.suppliers(
 id uuid primary key default gen_random_uuid(),company_id uuid not null references public.companies(id) on delete cascade,name text not null,tax_id text,email text,phone text,address text,payment_terms_days integer not null default 30,status text not null default 'active' check(status in('active','inactive')),notes text,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(company_id,name));
create table if not exists public.purchase_orders(
 id uuid primary key default gen_random_uuid(),company_id uuid not null references public.companies(id) on delete cascade,restaurant_id uuid not null references public.restaurants(id) on delete cascade,supplier_id uuid references public.suppliers(id) on delete set null,order_number text not null,order_date date not null default current_date,expected_date date,status text not null default 'draft' check(status in('draft','sent','partially_received','received','cancelled')),subtotal numeric(12,2) not null default 0,tax_amount numeric(12,2) not null default 0,total numeric(12,2) not null default 0,notes text,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(company_id,order_number));
create table if not exists public.purchase_order_lines(
 id uuid primary key default gen_random_uuid(),purchase_order_id uuid not null references public.purchase_orders(id) on delete cascade,description text not null,quantity numeric(12,3) not null default 1,unit text not null default 'ud',unit_price numeric(12,4) not null default 0,tax_rate numeric(5,2) not null default 21,received_quantity numeric(12,3) not null default 0);
create table if not exists public.purchase_invoices(
 id uuid primary key default gen_random_uuid(),company_id uuid not null references public.companies(id) on delete cascade,restaurant_id uuid not null references public.restaurants(id) on delete cascade,supplier_id uuid references public.suppliers(id) on delete set null,purchase_order_id uuid references public.purchase_orders(id) on delete set null,invoice_number text not null,invoice_date date not null default current_date,due_date date,status text not null default 'pending' check(status in('pending','approved','paid','cancelled')),subtotal numeric(12,2) not null default 0,tax_amount numeric(12,2) not null default 0,total numeric(12,2) not null default 0,currency text not null default 'EUR',notes text,created_at timestamptz not null default now(),unique(company_id,supplier_id,invoice_number));
create table if not exists public.purchase_documents(
 id uuid primary key default gen_random_uuid(),company_id uuid not null references public.companies(id) on delete cascade,restaurant_id uuid references public.restaurants(id) on delete cascade,supplier_id uuid references public.suppliers(id) on delete set null,file_name text not null,file_path text,document_type text not null default 'unknown' check(document_type in('unknown','invoice','delivery_note','receipt')),status text not null default 'pending' check(status in('pending','processing','reviewed','rejected')),document_date date,total numeric(12,2),notes text,created_at timestamptz not null default now());
create index if not exists suppliers_company_idx on public.suppliers(company_id,status);create index if not exists purchase_orders_restaurant_idx on public.purchase_orders(restaurant_id,status,order_date desc);create index if not exists purchase_invoices_restaurant_idx on public.purchase_invoices(restaurant_id,status,due_date);create index if not exists purchase_documents_company_idx on public.purchase_documents(company_id,status,created_at desc);
alter table public.suppliers enable row level security;alter table public.purchase_orders enable row level security;alter table public.purchase_order_lines enable row level security;alter table public.purchase_invoices enable row level security;alter table public.purchase_documents enable row level security;
do $$ declare t text; begin foreach t in array array['suppliers','purchase_orders','purchase_invoices','purchase_documents'] loop execute format('drop policy if exists company_members_access on public.%I',t);execute format('create policy company_members_access on public.%I for all to authenticated using(exists(select 1 from public.company_members cm where cm.company_id=%I.company_id and cm.user_id=auth.uid())) with check(exists(select 1 from public.company_members cm where cm.company_id=%I.company_id and cm.user_id=auth.uid()))',t,t,t);end loop;end $$;
drop policy if exists purchase_order_lines_access on public.purchase_order_lines;create policy purchase_order_lines_access on public.purchase_order_lines for all to authenticated using(exists(select 1 from public.purchase_orders po join public.company_members cm on cm.company_id=po.company_id where po.id=purchase_order_id and cm.user_id=auth.uid())) with check(exists(select 1 from public.purchase_orders po join public.company_members cm on cm.company_id=po.company_id where po.id=purchase_order_id and cm.user_id=auth.uid()));
grant select,insert,update,delete on public.suppliers,public.purchase_orders,public.purchase_order_lines,public.purchase_invoices,public.purchase_documents to authenticated;
commit;
